---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name:  Write Nginx site config
  ansible.builtin.template:
    src: nginx_site.conf.j2
    dest: "/etc/nginx/sites-available/{{ vault_app_name }}"
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Enable Nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ vault_app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ vault_app_name }}"
    state: link
  notify: reload nginx

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Ensure Nginx is started and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
