---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - ufw
      - htop           
    state: present

- name: Create app group
  ansible.builtin.group:
    name: "{{ app_group }}"
    system: true

- name: Create app system user
  ansible.builtin.user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    system: true
    shell: /bin/bash
    create_home: true
    home: "{{ app_root }}"

