---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - ufw
      - htop  
      - npm      
    state: present

- name: Create app group
  ansible.builtin.group:
    name: "{{ app_group }}"
    system: true

- name: Create app system user
  ansible.builtin.user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    system: true
    shell: /bin/bash
    create_home: true
    home: "{{ app_root }}"

- name: Create deploy group
  ansible.builtin.group:
    name: deploy
    state: present

- name: Create deploy user
  ansible.builtin.user:
    name: deploy
    group: deploy
    shell: /bin/bash
    create_home: yes
    system: no

- name: Add deploy user's SSH key for future deploys
  ansible.posix.authorized_key:
    user: deploy
    key: "{{ lookup('file', '../../../files/ansible.pub') }}"
    state: present

- name: Create app root directory
  become: true
  ansible.builtin.file:
    path: "{{ app_root }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
