vault_postgres_password: "change_me_strong_password"
vault_redis_password: "change_me_strong_password"
vault_app_env:
  NODE_ENV: production
  PORT: "3000"
  DATABASE_HOST: "127.0.0.1"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "{{ app_name }}_db"
  DATABASE_USER: "{{ app_name }}_user"
  DATABASE_PASSWORD: "{{ vault_postgres_password }}"
  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "{{ vault_redis_password }}"
  JWT_SECRET: "change_me_jwt_secret"
