# App servers
[webservers]
target01 ansible_host=13.49.243.193
# target01 ansible_host=ip_of_instance ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/iam-user.pem

# DB servers
[dbservers]
# db01 ansible_host=instance_ip
# Group all servers
[multi:children]
webservers
